// UIの多言語対応および翻訳テキストの定義を行う
use serde::{Deserialize, Serialize};

/// UI言語
#[derive(Clone, Copy, PartialEq, Debug, Serialize, Deserialize)]
pub enum Language {
    Japanese,
    English,
    #[serde(alias = "Chinese")]
    ChineseSimplified,
    ChineseTraditional,
    Korean,
}

impl Language {
    pub fn label(&self) -> &'static str {
        match self {
            Language::Japanese => "日本語",
            Language::English => "English",
            Language::ChineseSimplified => "简体中文",
            Language::ChineseTraditional => "繁體中文",
            Language::Korean => "한국어",
        }
    }

    pub const ALL: &'static [Language] = &[
        Language::Japanese,
        Language::English,
        Language::ChineseSimplified,
        Language::ChineseTraditional,
        Language::Korean,
    ];
}

/// UI文字列の翻訳テーブル
#[allow(dead_code)]
pub struct Tr {
    pub new_game: &'static str,
    pub new_game_tooltip: &'static str,
    // --- 右パネル ---
    pub comment: &'static str,
    pub notation: &'static str,
    pub sgf: &'static str,
    pub portal_v1: &'static str,
    pub portal_v2: &'static str,
    pub copy: &'static str,
    pub cut: &'static str,
    pub paste: &'static str,

    // --- ツールバー ---
    pub show_numbers: &'static str,
    pub settings: &'static str,
    pub open_file: &'static str,
    pub save_as: &'static str,
    pub undo_all: &'static str,
    pub undo_one: &'static str,
    pub redo_one: &'static str,
    pub redo_all: &'static str,
    pub settings_tooltip: &'static str,
    pub open_file_tooltip: &'static str,
    pub save_as_tooltip: &'static str,
    pub undo_all_tooltip: &'static str,
    pub undo_one_tooltip: &'static str,
    pub redo_one_tooltip: &'static str,
    pub redo_all_tooltip: &'static str,

    // --- 設定ウィンドウ ---
    pub settings_title: &'static str,
    pub board_section: &'static str,
    pub board_color: &'static str,
    pub encoding_section: &'static str,
    pub encoding_label: &'static str,
    pub language_section: &'static str,
    pub language_label: &'static str,
    pub max_nodes_label: &'static str,
    pub font_section: &'static str,
    pub font_label: &'static str,
    pub font_select: &'static str,
    pub save: &'static str,
    pub stone_shading: &'static str,
    pub show_branches: &'static str,
    pub show_branch_text: &'static str,
    pub show_branch_count: &'static str,

    // --- 削除確認 ---
    pub delete_confirm_title: &'static str,
    pub delete_confirm_msg: &'static str,
    pub delete_yes: &'static str,
    pub delete_no: &'static str,
    pub save_overwrite: &'static str,
    pub save_as_menu: &'static str,
    pub save_branch: &'static str,
    pub top_branch_highlight_count: &'static str,
    pub last_move_color_label: &'static str,
    pub new_game_confirm_title: &'static str,
    pub new_game_confirm_msg: &'static str,
    pub copied_to_clipboard: &'static str,
    pub vcf: &'static str,
    pub vcf_shortest: &'static str,
    pub vcf_long: &'static str,
    pub vcf_solving: &'static str,
    pub vcf_cancel: &'static str,
    pub vcf_replay_start: &'static str,
    pub vcf_replay_prev: &'static str,
    pub vcf_replay_next: &'static str,
    pub vcf_replay_end: &'static str,
    pub vcf_section: &'static str,
    pub show_forbidden_points: &'static str,
    pub vcf_mode: &'static str,
    pub vcf_depth: &'static str,
    pub vcf_timeout: &'static str,
}

pub fn get(lang: Language) -> &'static Tr {
    match lang {
        Language::Japanese => &TR_JA,
        Language::English => &TR_EN,
        Language::ChineseSimplified => &TR_ZH,
        Language::ChineseTraditional => &TR_ZHT,
        Language::Korean => &TR_KO,
    }
}

static TR_JA: Tr = Tr {
    new_game: "📄",
    new_game_tooltip: "新規作成 (リセット)",
    comment: "コメント",
    notation: "棋譜",
    sgf: "SGF",
    portal_v1: "Portal V1",
    portal_v2: "Portal V2",
    copy: "📋 コピー",
    cut: "✂ 切り取り",
    paste: "📋 貼り付け",

    show_numbers: "石番号を表示",
    settings: "⚙",
    open_file: "📁",
    save_as: "💾",
    undo_all: "|<",
    undo_one: "<",
    redo_one: ">",
    redo_all: ">|",
    settings_tooltip: "設定",
    open_file_tooltip: "ファイルを開く",
    save_as_tooltip: "名前を付けて保存",
    undo_all_tooltip: "全て戻す",
    undo_one_tooltip: "一手戻す",
    redo_one_tooltip: "一手進める",
    redo_all_tooltip: "全て進める",

    settings_title: "⚙ 設定",
    board_section: "盤面",
    board_color: "盤の色:",
    encoding_section: "言語 / エンコーディング",
    encoding_label: "Text及びコメントのデコードに使用:",
    language_section: "UI言語",
    language_label: "表示言語:",
    max_nodes_label: "最大読み込みノード数:",
    font_section: "フォント",
    font_label: "使用フォント:",
    font_select: "選択...",
    save: "💾 保存",
    stone_shading: "石に陰影をつける",
    show_branches: "分岐を表示する",
    show_branch_text: "テキストを表示",
    show_branch_count: "分岐数を表示",
    delete_confirm_title: "削除の確認",
    delete_confirm_msg: "現在の着手とその先にある全ての分岐を削除しますか？",
    delete_yes: "はい",
    delete_no: "いいえ",
    save_overwrite: "上書き保存",
    save_as_menu: "名前を付けて保存",
    save_branch: "分岐を保存",
    top_branch_highlight_count: "強調表示する上位候補数:",
    last_move_color_label: "最新の着手番号の色:",
    new_game_confirm_title: "新規作成の確認",
    new_game_confirm_msg: "現在の内容をリセットして新規作成しますか？",
    copied_to_clipboard: "クリップボードにコピーしました",
    vcf: "VCF",
    vcf_shortest: "四追い(最短)",
    vcf_long: "四追い(長手数)",
    vcf_solving: "探索中",
    vcf_cancel: "VCF探索を停止",
    vcf_replay_start: "VCF手順を先頭へ",
    vcf_replay_prev: "VCF手順を1手戻す",
    vcf_replay_next: "VCF手順を1手進める",
    vcf_replay_end: "VCF手順を最後まで表示",
    vcf_section: "VCF / 禁手",
    show_forbidden_points: "黒番の禁手を赤いXで表示",
    vcf_mode: "探索方式:",
    vcf_depth: "探索深さ:",
    vcf_timeout: "思考時間(秒):",
};

static TR_EN: Tr = Tr {
    new_game: "📄",
    new_game_tooltip: "New Game",
    comment: "Comment",
    notation: "Notation",
    sgf: "SGF",
    portal_v1: "Portal V1",
    portal_v2: "Portal V2",
    copy: "📋 Copy",
    cut: "✂ Cut",
    paste: "📋 Paste",

    show_numbers: "Show move numbers",
    settings: "⚙",
    open_file: "📁",
    save_as: "💾",
    undo_all: "|<",
    undo_one: "<",
    redo_one: ">",
    redo_all: ">|",
    settings_tooltip: "Settings",
    open_file_tooltip: "Open File",
    save_as_tooltip: "Save As",
    undo_all_tooltip: "Undo All",
    undo_one_tooltip: "Undo One",
    redo_one_tooltip: "Redo One",
    redo_all_tooltip: "Redo All",

    settings_title: "⚙ Settings",
    board_section: "Board",
    board_color: "Board color:",
    encoding_section: "Encoding",
    encoding_label: "Decoding for Text and Comments:",
    language_section: "UI Language",
    language_label: "Language:",
    max_nodes_label: "Max nodes to load:",
    font_section: "Font",
    font_label: "Font path:",
    font_select: "Select...",
    save: "💾 Save",
    stone_shading: "Shaded stones",
    show_branches: "Show branches",
    show_branch_text: "Show text",
    show_branch_count: "Show branch count",
    delete_confirm_title: "Confirm Deletion",
    delete_confirm_msg: "Delete this move and all subsequent branches?",
    delete_yes: "Yes",
    delete_no: "No",
    save_overwrite: "Save",
    save_as_menu: "Save As",
    save_branch: "Save Branch",
    top_branch_highlight_count: "Top branch highlight count:",
    last_move_color_label: "Last move number color:",
    new_game_confirm_title: "Confirm New Game",
    new_game_confirm_msg: "Reset current content and start a new game?",
    copied_to_clipboard: "Copied to clipboard",
    vcf: "VCF",
    vcf_shortest: "VCF (shortest)",
    vcf_long: "VCF (long)",
    vcf_solving: "Solving",
    vcf_cancel: "Stop VCF search",
    vcf_replay_start: "Go to first VCF move",
    vcf_replay_prev: "Step VCF back",
    vcf_replay_next: "Step VCF forward",
    vcf_replay_end: "Show all VCF moves",
    vcf_section: "VCF / Forbidden",
    show_forbidden_points: "Show forbidden black moves with red X",
    vcf_mode: "Search mode:",
    vcf_depth: "Search depth:",
    vcf_timeout: "Time limit (sec):",
};

static TR_ZH: Tr = Tr {
    new_game: "📄",
    new_game_tooltip: "新建 (重置)",
    comment: "注释",
    notation: "棋谱",
    sgf: "SGF",
    portal_v1: "Portal V1",
    portal_v2: "Portal V2",
    copy: "📋 复制",
    cut: "✂ 剪切",
    paste: "📋 粘贴",

    show_numbers: "显示手数",
    settings: "⚙",
    open_file: "📁",
    save_as: "💾",
    undo_all: "|<",
    undo_one: "<",
    redo_one: ">",
    redo_all: ">|",
    settings_tooltip: "设置",
    open_file_tooltip: "打开文件",
    save_as_tooltip: "另存为",
    undo_all_tooltip: "回到開始",
    undo_one_tooltip: "悔一步",
    redo_one_tooltip: "进一步",
    redo_all_tooltip: "到最后",

    settings_title: "⚙ 设置",
    board_section: "棋盘",
    board_color: "棋盘颜色:",
    encoding_section: "编码",
    encoding_label: "文字和注释的解码方式:",
    language_section: "界面语言",
    language_label: "语言:",
    max_nodes_label: "最大读取节点数:",
    font_section: "字体",
    font_label: "使用字体:",
    font_select: "选择...",
    save: "💾 保存",
    stone_shading: "显示阴影",
    show_branches: "显示分支",
    show_branch_text: "显示注释",
    show_branch_count: "显示分支数",
    delete_confirm_title: "确认删除",
    delete_confirm_msg: "确定要删除当前的着手及其后的所有分支吗？",
    delete_yes: "是",
    delete_no: "否",
    save_overwrite: "保存",
    save_as_menu: "另存为",
    save_branch: "保存分支",
    top_branch_highlight_count: "高亮显示的前几位分支数:",
    last_move_color_label: "最新着手的手数颜色:",
    new_game_confirm_title: "确认新建",
    new_game_confirm_msg: "确定要重置当前内容并新建吗？",
    copied_to_clipboard: "已复制到剪贴板",
    vcf: "VCF",
    vcf_shortest: "四追(最短)",
    vcf_long: "四追(长手数)",
    vcf_solving: "搜索中",
    vcf_cancel: "停止VCF搜索",
    vcf_replay_start: "回到VCF首手",
    vcf_replay_prev: "VCF后退一手",
    vcf_replay_next: "VCF前进一手",
    vcf_replay_end: "显示全部VCF手顺",
    vcf_section: "VCF / 禁手",
    show_forbidden_points: "用红色X显示黑方禁手",
    vcf_mode: "搜索方式:",
    vcf_depth: "搜索深度:",
    vcf_timeout: "思考时间(秒):",
};

static TR_ZHT: Tr = Tr {
    new_game: "📄",
    new_game_tooltip: "新增 (重設)",
    comment: "註釋",
    notation: "棋譜",
    sgf: "SGF",
    portal_v1: "Portal V1",
    portal_v2: "Portal V2",
    copy: "📋 複製",
    cut: "✂ 剪下",
    paste: "📋 貼上",

    show_numbers: "顯示手數",
    settings: "⚙",
    open_file: "📁",
    save_as: "💾",
    undo_all: "|<",
    undo_one: "<",
    redo_one: ">",
    redo_all: ">|",
    settings_tooltip: "設置",
    open_file_tooltip: "打開文件",
    save_as_tooltip: "另存為",
    undo_all_tooltip: "回到開始",
    undo_one_tooltip: "悔一步",
    redo_one_tooltip: "進一步",
    redo_all_tooltip: "到最後",

    settings_title: "⚙ 設置",
    board_section: "棋盤",
    board_color: "棋盤顏色:",
    encoding_section: "編碼",
    encoding_label: "文字和註釋的解碼方式:",
    language_section: "界面語言",
    language_label: "語言:",
    max_nodes_label: "最大讀取節點數:",
    font_section: "字體",
    font_label: "使用字體:",
    font_select: "選擇...",
    save: "💾 保存",
    stone_shading: "顯示陰影",
    show_branches: "顯示分支",
    show_branch_text: "顯示註釋",
    show_branch_count: "顯示分支數",
    delete_confirm_title: "確認刪除",
    delete_confirm_msg: "確定要刪除目前的著手及其後的所有分支嗎？",
    delete_yes: "是",
    delete_no: "否",
    save_overwrite: "儲存",
    save_as_menu: "另存為",
    save_branch: "儲存分支",
    top_branch_highlight_count: "高亮顯示的前幾位分支數:",
    last_move_color_label: "最新着手的手數顏色:",
    new_game_confirm_title: "確認新增",
    new_game_confirm_msg: "確定要重設目前內容並新增嗎？",
    copied_to_clipboard: "已複製到剪貼簿",
    vcf: "VCF",
    vcf_shortest: "四追(最短)",
    vcf_long: "四追(長手數)",
    vcf_solving: "搜尋中",
    vcf_cancel: "停止VCF搜尋",
    vcf_replay_start: "回到VCF首手",
    vcf_replay_prev: "VCF後退一手",
    vcf_replay_next: "VCF前進一手",
    vcf_replay_end: "顯示全部VCF手順",
    vcf_section: "VCF / 禁手",
    show_forbidden_points: "以紅色X顯示黑方禁手",
    vcf_mode: "搜尋方式:",
    vcf_depth: "搜尋深度:",
    vcf_timeout: "思考時間(秒):",
};

static TR_KO: Tr = Tr {
    new_game: "📄",
    new_game_tooltip: "새 ゲーム (초기화)",
    comment: "코멘트",
    notation: "기보",
    sgf: "SGF",
    portal_v1: "Portal V1",
    portal_v2: "Portal V2",
    copy: "📋 복사",
    cut: "✂ 잘라내기",
    paste: "📋 붙여넣기",

    show_numbers: "수순 표시",
    settings: "⚙",
    open_file: "📁",
    save_as: "💾",
    undo_all: "|<",
    undo_one: "<",
    redo_one: ">",
    redo_all: ">|",
    settings_tooltip: "설정",
    open_file_tooltip: "파일 열기",
    save_as_tooltip: "다른 이름으로 저장",
    undo_all_tooltip: "처음으로",
    undo_one_tooltip: "한 수 뒤로",
    redo_one_tooltip: "한 수 앞으로",
    redo_all_tooltip: "끝으로",

    settings_title: "⚙ 설정",
    board_section: "바둑판",
    board_color: "판 색상:",
    encoding_section: "인코딩",
    encoding_label: "텍스트 및 코멘트 디코딩:",
    language_section: "UI 언어",
    language_label: "언어:",
    max_nodes_label: "최대 노드 수:",
    font_section: "글꼴",
    font_label: "사용 글꼴:",
    font_select: "선택...",
    save: "💾 저장",
    stone_shading: "돌에 음영 넣기",
    show_branches: "분기 표시",
    show_branch_text: "텍스트 표시",
    show_branch_count: "분기 수 표시",
    delete_confirm_title: "삭제 확인",
    delete_confirm_msg: "현재 수순과 그 이후의 모든 분기를 삭제하시겠습니까?",
    delete_yes: "예",
    delete_no: "아니오",
    save_overwrite: "저장",
    save_as_menu: "다른 이름으로 저장",
    save_branch: "분기 저장",
    top_branch_highlight_count: "강조 표시할 상위 분기 수:",
    last_move_color_label: "마지막 수의 숫자 색상:",
    new_game_confirm_title: "새 게임 확인",
    new_game_confirm_msg: "현재 내용을 초기화하고 새 게임을 시작하시겠습니까?",
    copied_to_clipboard: "클립보드에 복사되었습니다",
    vcf: "VCF",
    vcf_shortest: "VCF(최단)",
    vcf_long: "VCF(장수순)",
    vcf_solving: "탐색 중",
    vcf_cancel: "VCF 탐색 중지",
    vcf_replay_start: "VCF 첫 수로 이동",
    vcf_replay_prev: "VCF 한 수 뒤로",
    vcf_replay_next: "VCF 한 수 앞으로",
    vcf_replay_end: "VCF 전체 수순 표시",
    vcf_section: "VCF / 금수",
    show_forbidden_points: "흑 금수를 빨간 X로 표시",
    vcf_mode: "탐색 방식:",
    vcf_depth: "탐색 깊이:",
    vcf_timeout: "제한 시간(초):",
};
